### ISSUE TITLE
Remove utm_* from any link?

### ISSUE THREAD

**Issue by OhSoGood** [einaregilsson/Redirector#114]
Hi,

Thank you for this excellent extension that I've recently only discovered.

I was wondering if it is possible with this extension to remove all utm_* (utm_source, utm_campaign, utm_medium, utm_term...) from any url with one single redirection rule. If so, could you help me find the right regex? Would it have a significant/noticeable cost (in duration)?

Regards

**Comment by einaregilsson** [comment]
Hi. Would be pretty complicated to get every one of them, since they might be in different order in different urls. It's certainly possible with some big regex but it would probably get pretty complicated.

This sounds more like something that would make sense to make its own extension for, and just hardcode into it the replacement of utm_* in all urls. That would be pretty trivial to create.

**Comment by anewuser** [comment]
This is actually very simple. Just create a redirection from `(.*?)(\&|\?)_?utm` to `$1`

"utm" tracking parameters are added to the end of URLs, so there's no harm in removing everything that follows the first occurrence of  `?utm`  or `&utm`, `?_utm` or `&_utm` (all covered by my suggested regex).

**Comment by anewuser** [comment]
You can use this: https://addons.mozilla.org/addon/clean-links-webext/

I personally use this now: https://addons.mozilla.org/addon/requestcontrol/

**Comment by gkrishnaks** [comment]
Cool, I'll check how it's done in these add-ons to implement it in mine. Thanks :)

**Comment by einaregilsson** [comment]
Closing this, since it's a request for help with a rule, not an issue with the extension itself.

**Comment by grahamperrin** [comment]
Recommended for Firefox: [ClearURLs](https://addons.mozilla.org/addon/clearurls/).
