### ISSUE TITLE
Firefox: icon blends into browser chrome.

### ISSUE THREAD

**Issue by shortenjukebox** [einaregilsson/Redirector#141]
I use the built-in dark theme in Firefox, and it just so happens that the Redirector icon, when it’s enabled, is the exact same color as the browser toolbar.

**Comment by einaregilsson** [comment]
Ok, I'll try to include dark mode icons when I next update Redirector.

**Comment by Vulgaris-Viridis** [comment]
Please don't change the icon - it's perfect as it is. This is one of those "set and forget" addons, and having the icon that blends into the theme is a perfect design. I wish more devs would do that.

@shortenjukebox i could understand if it is an icon for the uBlock origin, uMatrix or noScript...something you use daily and multiple times, but for the sake of my curiosity just how many times a day do you set a new redirect?

**Comment by shortenjukebox** [comment]
@Vulgaris-Viridis I’m willing to concede the issue to you if you find it useful. I do click the icon often since I often enable/disable the extension, but the icon blending in is not a significant usability issue for me personally.

However, I was just thinking of other users who may have visual impairments where this presents another obstacle for them. Plus, if one customizes their Firefox browser chrome in a possible (yet albeit unlikely) way, there’s a potential problem.

![Screen Shot 2019-04-22 at 12 59 48](https://user-images.githubusercontent.com/4441542/56512864-24118e80-6520-11e9-9e26-53e5065127d3.png)

Scenario: I’ve installed Redirector, but where is it?!

![Screen Shot 2019-04-22 at 12 58 41](https://user-images.githubusercontent.com/4441542/56512813-fcbac180-651f-11e9-9248-ba4f474ff292.png)

Ah, there it is! In between two flexible space elements. Silly me.

![Screen Shot 2019-04-22 at 13 01 42](https://user-images.githubusercontent.com/4441542/56512952-6a66ed80-6520-11e9-9cc6-3a0d5c90a468.png)

Again, not a huge usability concern for most users, but it’s just that it may have unexpected results, which is definitively not the best user experience design.

**Comment by Vulgaris-Viridis** [comment]
> I do click the icon often since I often enable/disable the extension
I agree, icon is not as visible with the dark theme, i won't argue that, my original question was related to your personal usage of the extension and unusual circumstances under which you'd have to "often enable/disable the extension". 
One might argue that someone who specifically installs this extension would be "proficient enough" to know how to deal with blank ff spaces, but since @einaregilsson already agreed to implement a modified icon, i don't think that would bring any value to the discussion. I pin the extension to the overflow menu anyways so i won't be bothered by the alternate icon design anyways.

**Comment by Vulgaris-Viridis** [comment]
> I do click the icon often since I often enable/disable the extension

I agree, icon is not as visible with the dark theme, i won't argue that, my original question was related to your personal usage of the extension and unusual circumstances under which you'd have to "often enable/disable the extension". 
One might argue that someone who specifically installs this extension would be "proficient enough" to know how to deal with blank ff spaces, but since @einaregilsson already agreed to implement a modified icon, i don't think that would bring any value to the discussion. I pin the extension to the overflow menu anyways so i won't be bothered by the alternate icon design anyways.

**Comment by einaregilsson** [comment]
I definitely think it should be fixed for the dark theme. I'm just not really working much on this extension anymore, but when I do an update I'll definitely fix the icon.

**Comment by Vulgaris-Viridis** [comment]
@einaregilsson Well it does the job so thank you for maintaining it. As for the icon, my priority was always functionality over aesthetic so i won't hold any appearance design flaws against you.

**Comment by einaregilsson** [comment]
Dark mode is implemented in version 3.5 which is pending review and should be out in a few days.
