### ISSUE TITLE
Make extension act earlier, ie. before search

### ISSUE THREAD

**Issue by idkCpp** [einaregilsson/Redirector#153]
Hi. I love your extension but I have a little problem with it.

I use the extension at work to access my Jira Tickets. For example if I have to go the ticket ABC-123 I just want to type `ABC-123` and it redirects to `https://jira.my-company.com/browse/ABC-123`.

So when I set it up like `([A-Z]+-[0-9]+)` it works, but when I set it up like `^([A-Z]+-[0-9]+)$` it does not. I suspect this is because the query `ABC-123` turns into `https://duckduckgo.com/?q=ABC-123` which is then replaced. 

While it can be worked around I find it annoying.
I'm on Firefox 60.7.1esr

Thanks
idk.cpp

**Comment by einaregilsson** [comment]
The extension operates at the http request level, so it doesn't see anything until your browser starts to make an actual http request. We don't operate on the address bar itself, so we don't see the ABC-123 you type in. We currently have no plans to change this (especially since I'm basically not working much on this extension anymore, just keeping it in maintenance mode)
