### ISSUE TITLE
Unable to redirect from Twitter

### ISSUE THREAD

**Issue by Mrfiregem** [einaregilsson/Redirector#160]
As the title says. The console doesn't really give any information either, from what I can tell. May have to do with their new design

**Comment by einaregilsson** [comment]
Twitter uses a lot of ajax requests and history API to change pages, so it's unlikely that it will work well with Redirector. What is the specific redirect you were trying?

**Comment by Mrfiregem** [comment]
The second entry in the example below is the actual redirect, but the first wildcard one doesn't work either:

```
{
            "description": "test",
            "exampleUrl": "https://twitter.com/ProjectNXdev/status/1189770264348954625",
            "exampleResult": "github.com",
            "error": null,
            "includePattern": "*twitter.com*",
            "excludePattern": "",
            "patternDesc": "",
            "redirectUrl": "github.com",
            "patternType": "W",
            "processMatches": "noProcessing",
            "disabled": false,
            "appliesTo": [
                "main_frame"
            ]
        },
        {
            "description": "Twitter -> Nitter",
            "exampleUrl": "https://twitter.com/ArchdanMiiverse/status/1180528074888101888",
            "exampleResult": "https://nitter.net/ArchdanMiiverse/status/1180528074888101888",
            "error": null,
            "includePattern": "^https?:\\/\\/(?:.*\\.)?twitter\\.com\\/(.*(?=\\/status\\/).*)$",
            "excludePattern": "",
            "patternDesc": "Redirect tweets to alt frontend",
            "redirectUrl": "https://nitter.net/$1",
            "patternType": "R",
            "processMatches": "noProcessing",
            "disabled": true,
            "appliesTo": [
                "main_frame"
            ]
        }
}
```

**Comment by einaregilsson** [comment]
I would guess that the second would work if you tried to click a link outside twitter to that url, but when you're inside Twitter it probably doesn't work because of the way they load their pages. Maybe one day I'll make Redirector handle changes in the url bar itself, not just at the request level and then this would be possible, but for now sites like Twitter, Facebook etc. don't really work well with Redirector.

**Comment by Mrfiregem** [comment]
The redirects don't work at all, no matter if it's a link from on the site or externally

**Comment by einaregilsson** [comment]
Ok, those don't even match when you input them in the edit window. Something like this works when you come from outside twitter:

![Screenshot 2019-11-05 at 14 23 38](https://user-images.githubusercontent.com/557149/68215923-fa114c80-ffd7-11e9-9581-834190d12706.png)

but won't match once you're on twitter, since they use some ajax stuff and the history api to show the single tweets.

The first one works if you put in "https://github.com" as the redirect to, it has to resolve to an actual url, including the scheme. I should probably add a warning in the UI if it doesn't though.

**Comment by Mrfiregem** [comment]
Your example doesn't work either when I click a twitter link above from Github. Not sure why you say my example doesn't match
![image](https://user-images.githubusercontent.com/5158194/68269522-12a95300-0028-11ea-8fbc-de3341ef8e9a.png)

**Comment by einaregilsson** [comment]
Ok, looked more into this. I must have made an input error when I tested for the first time, the pattern is fine. And it works in Firefox, so I assume you're running Chrome? I tested in Chrome, turned on logging and found out that we were logging every url except Twitter urls. Looked further into it and it seems to be because Twitter is using a Service Worker to cache stuff and handle requests. So for now Redirector doesn't work with Twitter. There is a workaround which is to open dev tools, go to Application->Service Workers and check the "bypass for Network" box. But I don't know if that sticks when you close and re-open your browser.

In any case, sorry, I guess Redirector is not going to work for your use case. I guess it's time to start updating it and handle the actual url bar address, as well as the http requests...

**Comment by Mrfiregem** [comment]
I am using Firefox. This turned out to just be a cache or site setting bug. I was testing on another computer and it worked fine, so I tried using the history cleanup tool and it worked. Thanks for putting up with this.

Not sure if you want to keep this issue open to track the Chrome issue or create another issue altogether so I'll leave it open

**Comment by Mrfiregem** [comment]
Actually, the problem still happens on the initial browser, but hard-reloading the twitter page redirects it. Still no issues with other browsers

**Comment by einaregilsson** [comment]
I'll take a closer look at this before the next release. Pretty sure the problem on Firefox is probably also related to service workers handling requests.

**Comment by einaregilsson** [comment]
Version 3.5 which is pending review adds a new type of redirect, "HistoryState", which should do the trick of redirecting this.

**Comment by KaKi87** [comment]
Hello, I'm trying to redirect Twitter to a [Nitter](https://github.com/zedeus/nitter) instance, although Redirector isn't able to do it, a [dedicated extension](https://github.com/SimonBrazell/nitter-redirect) does it, could you please see what allows it to work and reproduce it ? Thanks.

**Comment by einaregilsson** [comment]
Sorry, I'm not really working on Redirector at the moment. Maybe someday I'll get back to it.
