### ISSUE TITLE
would you suppot sync and restartless

### ISSUE THREAD

**Issue by ivysrono** [einaregilsson/Redirector#3]
these are so useful for someone just like me ,who have more than one computer.

these are working in chrome redirector.

**Comment by dkaksl** [comment]
@einaregilsson who is making the Chrome Redirector? Is it not this same codebase?

I might just pick the task up myself; too many chrome extensions are missing (optional) automatic sync.

**Comment by einaregilsson** [comment]
@dkaksl This is a really old issue. There was (or is) another Chrome extension called Redirector, which is similar to mine but less configurable.

Two years after this issue was created I changed my Redirector extension to use the WebExtensions API and released it for Firefox, Chrome and Opera. So, yes, I have a Chrome extension now, although I didn't at the time of this issue.

**Comment by dkaksl** [comment]
@einaregilsson OK, but will it ever support automatic sync of redirects between devices? Should I open a new issue?

**Comment by einaregilsson** [comment]
Yes, open a new issue. It should be just a matter of changing chrome.storage.local to chrome.storage.sync in background.js. I didn't do it initially because then Firefox didn't support storage.sync, I don't know if they do it now. But there's also a migration issue, moving people's redirects from local to sync, make sure to not make people lose their data etc. The best idea might be to add an option to sync redirects, and only then use chrome.storage.sync.

**Comment by dkaksl** [comment]
@einaregilsson on it. I agree, the setting should probably be optional.
