### ISSUE TITLE
random data loss

### ISSUE THREAD

**Issue by elandorr** [einaregilsson/Redirector#301]
On a windows 10 box with FF 91.6.1esr all redirects are suddenly gone. Let me know if there's any log that might be helpful. The only recent action was clearing history/cache/everything, but I doubt you'd store them in there.

**Comment by Gitoffthelawn** [comment]
Has this happened again?  I'm guessing it was a rare Firefox profile corruption (not related to Redirector).  Historically, I've seen it reported over the years, but Mozilla has improved things to make it much, much less common.

Note also that AntiVirus/AntiMalware software accessing Firefox profile files at the same time as Firefox can cause corruption issues.

**Comment by Gitoffthelawn** [comment]
Yes, just blocking time-wasting sites can be a great choice.  Pi-hole is a great tool to do that at a lower level.

FF is stable for me, but everyone certainly has their own experiences with everything.  One practice I've gotten in to is to let it "settle" for 2-3 seconds after I open it (nice time to take a deep breath), and also let the system settle for 2-3 seconds after I close it (another nice breath).  I have no idea if that's really helping anything, but things work well, and I get a chance to take a couple nice deep breaths!

If you have time, perhaps file a bug report or two (or ten) on [Mozilla's Bugzilla](https://bugzilla.mozilla.org) to let them know the issues you are having.  The issues on Debian are probably the most important to report, as I think they are a little short on Debian testers right now.

**Comment by elandorr** [comment]
The 'settlement' is needed here anyhow due to speed :). Even on a minimal Debian setup with some average CPU it takes far longer than 2 seconds for it to be usable. Chrom* is far faster/more reliable, but, well Google. Yes, pi-hole is nice. I don't have a separate system though and use [agh](https://github.com/AdguardTeam/AdGuardHome) locally. Eats quite some RAM because it keeps it all in there all the time, but no other way to handle it right now. I wouldn't mind that few milliseconds more to just read from a db, but give me my memory back.

I reported bugs like a paid tester for many years, 9/10 times Mozilla simply doesn't care. There are open bugs for 15 years, many important bugs for 10+. Major ones breaking the web that people just learned to work around with hackjobs. They've been a typical greedy corporation for a long time now, complete with extremely rich 'management' and billions of dollars in ad deals, jet-set 'speaker' scum etc. (all while accepting donations, of course, the usual non-profit lie where a commercial entity is ultimately in control anyway)
At the same time, they're very busy adding more spying and removing user control. Reading their bugtracker discussions is like watching any other corporate psychopaths. ('to /help/ you, we'll force you to be probed. yay, all hail the <brand> /helper/!') Making billions off the 'uh open source ooga booga' marketing they shove in your face, while violating basic user rights. (They remove, and worse, flat out ignore (so you think it did something, but it's a lie) all relevant flags by now, you cannot get the thing to shut up!) Chrom* with the ungoogled patch is now more user-respecting than FF!

Fixing their trash is impossible due to the absolutely massive size not even their own developers comprehend at this point. You couldn't build it anyway. On an average computer a normal person post-2020 could possibly afford after saving for years, it will build for a full day or more at 99C, or even OOM, as it requires boatloads of RAM.
There's no real living fork as far as I'm aware. Waterfox might be closest.

I still use FF for the plugins, but it's a shell of the promise of an open source browser. There was never any open source culture in any of it. To top it off, they're one of the new 'CoC' hypocrites who are more fascist than Hitler ever was. They only allow you to exist, if you parrot them 1:1. Contribute high quality reports and code, get banned. Say you're gay, get a jet-set lifestyle as a 'speaker' in luxury hotels paid for by donations. I'm not giving them another second of my lifetime.

The Debian version patches nothing relevant to their typical bugs: https://sources.debian.org/patches/firefox-esr/102.6.0esr-1/ I found FF just needs constant restarts and low tab numbers to be stable. That's just 'accepted' now. But a session saving plugin of your choice is helpful anyway to avoid that one inevitable crash killing days worth of your research.
The [BSP+ guy](https://github.com/aaFn/Bookmark-search-plus-2) is probably the best to talk to, he is very dedicated and built a far superior project than Mozilla ever has. Incredible someone put that effort into a really non-profit plugin. He uses every trick in the book to keep it responsive, even after Mozilla killed XUL. You really feel he cares, which is something you won't ever find in corpo.

Waterfox is also an ordinary corpo now. There is no living, true open source, apart from small plugins. And even they whore out. The 'idontcareaboutcookies' guy recently sold out to a many times proven malware abuser! It's literally not even any effort, you and me could replicate it easily. But he managed to 'monetize' his userbase. All greed, all the time.

At the size of the modern web, with all its abusive bloat that changes weekly, it also seems to be impossible to have real open source now. The billionaires dictate what's on the web. We are forced to use the web, as governments brutally enforce digital abuse. (Cash, anyone? We live in dystopia! Try living like an actual human being in Sweden, it's impossible. You're just cattle to be exploited for profit. Monitored, forced under threat of death to use tech.) So we have no choice.

https://gophie.org/ or https://github.com/jansc/ncgopher + GPG e-mail would be nice, but that does not have addiction potential, so it's not popular. And no 'buy now - regret later' button capability.

Anyway, thanks for your efforts with redirector! I enjoyed it while I used it. Even if it's bizarre that such a thing even came to exist. I believe we need to stop working around trash and start taking action by simply refusing to consume. Constantly working around the abuse by elaborate and most often very time-consuming means supports the system, without any benefit to us. We help abuse ourselves for some cheap distraction. I realized this when I needed to find the umpteenth working instance of some of these forks (nitter,that youtube thing,etc). I probably spent dozens of days combined researching and working on stuff whose sole purpose is to exploit me anyway. And it doesn't even last - now you need to invest maintenance time. Eventually you end up self-hosting, which costs a lot of money. Maybe you make it public, but end up having to stop, as not even 0.01% of the addicts will donate to keep it up. And then you start all over :-$. Weird time to be alive.

Have nice week!

**Comment by Gitoffthelawn** [comment]
> The 'settlement' is needed here anyhow due to speed :). Even on a minimal Debian setup with some average CPU it takes far longer than 2 seconds for it to be usable. Chrom* is far faster/more reliable, but, well Google. 

Yes, this is the current conundrum.  There really isn't an ideal web browser, yet web browsers are likely the most popular application used in the modern computing ecosystem.  I find Firefox to be the best compromise, but it definitely involves a few compromises.

I hadn't tried Chrome in a while, so I gave it another try recently.  I was surprised how awful it was.  Basic functionality that I take for granted in Firefox was completely missing from Chrome.  And, compared to Firefox, the UX in Chrome was just dreadful.  Plus, because Google controls Chrome, and I've had so many dreadful experiences with Google (a mega-corporation with horrible ethos), I just can't support them.

> I reported bugs like a paid tester for many years, 9/10 times Mozilla simply doesn't care. There are open bugs for 15 years, many important bugs for 10+. Major ones breaking the web that people just learned to work around with hackjobs.

I concur.  I filed bugs for many years, just to have Mozilla ignore many of them.  I think some of the bugs are still open on Bugzilla 10+ years later.  I got tired of performing *free work* for a corporation that pays their executives and developers such high salaries.  I'm not okay with them asking me to perform free work for them while they profit.

> They've been a typical greedy corporation for a long time now, complete with extremely rich 'management' and billions of dollars in ad deals, jet-set 'speaker' scum etc. (all while accepting donations, of course, the usual non-profit lie where a commercial entity is ultimately in control anyway).

Yes, I too struggle with the idea of providing free work for them while they pay themselves large salaries.  Seems rather egregious.  I sent them a letter asking them to perform some free work for me, but they didn't respond.

> At the same time, they're very busy adding more spying and removing user control. ... Making billions off the 'uh open source ooga booga' marketing they shove in your face, while violating basic user rights. (They remove, and worse, flat out ignore (so you think it did something, but it's a lie) all relevant flags by now, you cannot get the thing to shut up!) Chrom* with the ungoogled patch is now more user-respecting than FF!

Fortunately, all (?) the FF extraneous nonsense can be disabled.  I put a question mark there because I do have to spend time keeping both eyes on FF making sure it isn't doing anything inappropriate.  But I do feel, at least, Mozilla's heart is in the right place (even if their actions aren't always lined up with their heart).  On the other hand, Google's has a heart of cold stone.  Ironically, Google's actions occasionally betray its own empty heart, and it occasionally does something decent.  Of course, it's usually after it gets taken to court and loses.

> Fixing their trash is impossible due to the absolutely massive size not even their own developers comprehend at this point.

Unfortunately, I think this is true for all major web browsers at this point.  They have all become behemoths.  The open source browsers suffer from a lack of quality code commenting, which makes it much worse.  I've spent many hours going through the code of Firefox and Chrome, and neither is well-documented.

> You couldn't build it anyway. On an average computer a normal person post-2020 could possibly afford after saving for years, it will build for a full day or more at 99C, or even OOM, as it requires boatloads of RAM.

I've actually built it, but it does take a dedicated build machine running for many hours (or days, depending on the machine's specs).

> There's no real living fork as far as I'm aware. Waterfox might be closest.

Yes, Waterfox is currently alive and growing.  I've considered using Waterfox, but Firefox, with all my tweaks, works very well for me.  I don't think Waterfox would help me with anything (except perhaps slightly less RAM usage), but for those starting fresh, it seems like a great place to begin.

> I still use FF for the plugins, but it's a shell of the promise of an open source browser. There was never any open source culture in any of it. To top it off, they're one of the new 'CoC' hypocrites who are more fascist than Hitler ever was. They only allow you to exist, if you parrot them 1:1. Contribute high quality reports and code, get banned. Say you're gay, get a jet-set lifestyle as a 'speaker' in luxury hotels paid for by donations. I'm not giving them another second of my lifetime.

I strongly disagree with those words and I think they are very much over the top, but we are each entitled to our opinions.

> The Debian version patches nothing relevant to their typical bugs: https://sources.debian.org/patches/firefox-esr/102.6.0esr-1/ I found FF just needs constant restarts and low tab numbers to be stable. That's just 'accepted' now.

Yes, I too make a habit of frequent restarts and keep tab numbers low.  But I've been around enough years that I always assume computers are about to crash.  *The worst was Microsoft's Windows 3.1, which I think scarred me for life.*

> But a session saving plugin of your choice is helpful anyway to avoid that one inevitable crash killing days worth of your research. The [BSP+ guy](https://github.com/aaFn/Bookmark-search-plus-2) is probably the best to talk to, he is very dedicated and built a far superior project than Mozilla ever has. Incredible someone put that effort into a really non-profit plugin. He uses every trick in the book to keep it responsive, even after Mozilla killed XUL. You really feel he cares, which is something you won't ever find in corpo.

Yes, he is amazing and he does care.  If you go through that repo, you can see I try to help out there when I have time.  I'm not even using that extension right now, but I still try to help out because he does care, and the quality of his extension is that good.  Mozilla and Google could certainly learn a lot from him.

> Waterfox is also an ordinary corpo now.

I wasn't aware of this.  Can you expand?

> There is no living, true open source, apart from small plugins. And even they whore out. The 'idontcareaboutcookies' guy recently sold out to a many times proven malware abuser! It's literally not even any effort, you and me could replicate it easily. But he managed to 'monetize' his userbase. All greed, all the time.

Yes, much of this world is unfortunately so much about greed, greed, greed.  But not all of it.  And from what I've seen, when a developer isn't greedy, they tend to be from a few specific nations.  I don't want to get into any nation-bashing, but certain nations seem to create much more charitable people than other nations, while other nations do seem to largely create greedy, um, to use your word, *whores*.  **The solution: be kind and generous wherever on our little planet you originated.**

> At the size of the modern web, with all its abusive bloat that changes weekly, it also seems to be impossible to have real open source now. The billionaires dictate what's on the web.

Bloat, yes.  Abusive bloat, probably.  Billionaires dictating what's on the web?  Perhaps, but I don't spend much time on that part of the web.  I read/watch truly independent content, like your rant (and BTW, despite many people judging rants as something "bad", I think they can be quite constructive and interesting; for example, I'm appreciative of the one you took your time to thoughtfully write).

> We are forced to use the web, as governments brutally enforce digital abuse. (Cash, anyone? We live in dystopia! Try living like an actual human being in Sweden, it's impossible. You're just cattle to be exploited for profit. Monitored, forced under threat of death to use tech.) So we have no choice.

At this point, not using the web has gotten harder and harder.  I can go without using it, but some tasks have gotten quite difficult to complete these days without the web.  I choose not to waste away my days with "social networking".  Sadly, some young devs don't seem to understand that many of us do not have such accounts, nor do we want them.  Consequently, sometimes getting a task done without any "social networking" accounts can be daunting challenge.  And what if one doesn't want to have a smartphone lashed to them at all times like the proverbial ball and chain?

> Anyway, thanks for your efforts with redirector!

You, and all, are most welcome.  I think it's an excellent tool, and I have fond memories of interacting with Einar.  He really did a great job on it.  He kept working on it simply to help others, even though he was no longer using it himself.  **That type of altruism is an inspiration.**

> I believe we need to stop working around trash and start taking action by simply refusing to consume.

**I agree 100%.**  I go through periods of time where I literally refuse to consume anything except for a minimal amount of healthy food because so much of what is offered in our world is such trash.  *Such periods can be a great time to give to charity too.*

> Constantly working around the abuse by elaborate and most often very time-consuming means supports the system, without any benefit to us. We help abuse ourselves for some cheap distraction. I realized this when I needed to find the umpteenth working instance of some of these forks (nitter,that youtube thing,etc). I probably spent dozens of days combined researching and working on stuff whose sole purpose is to exploit me anyway. And it doesn't even last - now you need to invest maintenance time. Eventually you end up self-hosting, which costs a lot of money. Maybe you make it public, but end up having to stop, as not even 0.01% of the addicts will donate to keep it up. And then you start all over :-$. Weird time to be alive.

Yes, prioritizing what you really value in life, I think, is key.  And cheap distractions often aren't what we truly value.

> Have nice week!

You as well.  I enjoyed reading what you wrote.  I can tell you put quite a bit of time and thought into it, and really "put your thoughts onto paper", so to speak.  I hope, similarly, my comments are interesting to you.
