### ISSUE TITLE
[Support] How to set up the extension

### ISSUE THREAD

**Issue by bheeshmpita** [einaregilsson/Redirector#343]
I have read the wiki as well as the examples but unable to set it up and make it work. Kindly help me suggesting the changes.
I want to redirect reddit and youtube links, so i tried setting it up like this for reddit -

_Example URL:
https://reddit.com/r/mpv
Include pattern:
https://reddit.com/*
Redirect to:
https://libreddit.spike.codes/$1
Pattern type:
Wildcard
Example result:
https://libreddit.spike.codes/r/mpv_

I want to redirect the reddit links from google search to equivalent libreddit page.
Secondly what changes should I make so the extension is able to read only history relevant to these domains only instead of entire one.
Thanks

**Comment by Gitoffthelawn** [comment]
You are so close!

In the `Include pattern`, it looks like you need to add the host name for the domain.  Try adding `www.` before `reddit.com`.

Once you get that working, you may want to improve it a bit to handle both commonly used reddit hosts.  Many people prefer `old.reddit.com`, while some prefer `www.reddit.com`.

To make that work, you can simply create another rule, or use the power of regular expressions.  The regex for the include pattern should then be `^https://(?:old|www)\.reddit\.com/(.*)`

I just wrote that for you by hand (untested), so if it doesn't work for any reason, just let me know.

Don't forget to change the `Pattern type` flag too!

Regarding your question and reading history, Redirector actually doesn't read history, it just looks at current requests (well, it technically keeps its own tiny ephemeral history just to prevent infinite loops).  The hostnames it views cannot be restricted because it needs to be able to see all requests to see if they match any of the rules you create.

**Comment by bheeshmpita** [comment]
Thanks that worked! And thanks for the wonderful explanation too.

**Comment by Gitoffthelawn** [comment]
You're most welcome. Enjoy.
