### ISSUE TITLE
Empty blank window should be silenced

### ISSUE THREAD

**Issue by purpleidea** [einaregilsson/Redirector#46]
If you use this with another technique, you get a new window which is blank. This happens because of a href target that has _blank I think. If we could silence this or have an option to, that would be great. See article from my blog on how to use this excellent plugin you made, and a description of the bug.

https://ttboj.wordpress.com/2015/11/14/matching-arbitrary-urls-to-custom-firefox-profiles/

Thanks again!

**Comment by einaregilsson** [comment]
Nice example of using Redirector :) However, since the blank window thing is a general bug in Firefox I think it should be fixed there, not in Redirector. Also, the level which I’m working at in Redirector is the http level, my code knows nothing about windows, target=”_blank” or anything like that. I just monitor the requested urls and redirect them if they match a pattern.

**Comment by Gitoffthelawn** [comment]
@purpleidea Can you submit the bug to Mozilla via bugzilla so they can fix it?

**Comment by purpleidea** [comment]
@Gitoffthelawn I don't know how best to describe it in terms of technical merits, and I'm sure it's a known issue or a won't fix. I would probably be creating a dupe. If someone find the bz, LMK :)

Thanks!
