### ISSUE TITLE
Support for custom protocols such as "spotify:"

### ISSUE THREAD

**Issue by HatScripts** [einaregilsson/Redirector#92]
I wanted to redirect Spotify links like "spotify:track:..." to "https://open.spotify.com/track/...", so I added this redirection rule:

![redirection rule](https://cloud.githubusercontent.com/assets/5691865/23887025/40a0ec0e-08d3-11e7-8d25-e4a8dd64b899.png)

However, at least in Opera, it doesn't work. I just get this error when visiting "spotify:" links:

![error message](https://cloud.githubusercontent.com/assets/5691865/23887102/b6dff7c0-08d3-11e7-81ce-3706bd19407b.png)

I realise that the error message is because I don't have Spotify installed, but that's why I wish to redirect "spotify:" links to the equivalent Spotify Web Player url.

**Edit:** I just tried selecting all the checkboxes for the scopes to which to apply the redirection rule, but to no avail.

![image](https://cloud.githubusercontent.com/assets/5691865/23887295/f4f43b2e-08d4-11e7-9d17-a0614cb7d0f1.png)

**Comment by einaregilsson** [comment]
Sorry, the API I'm using only gives me access to the http and https protocols. There are ways of catching the other stuff, but I would have to use a completely different method for it, up in the UI, and I'm not really adding new features to this addon anymore. I'll leave this open though, if anyone wants to take a crack at it.

**Comment by thouters** [comment]
I'm also affected by this when trying to rewrite file:/// links to http://

**Comment by einaregilsson** [comment]
Yes, same answer, I only have access to http and https protocols for redirection. It's unlikely that Redirector will ever support anything else.

**Comment by einaregilsson** [comment]
It is due to restrictions in the API we use to redirect, yes. The browsers provide an API that gives you access to every http and https request that comes from the browser and you can redirect them, but that API doesn't allow other protocols.

However, it would be possible, if you only cared about urls that are actually shown in the address bar, not images, stylesheets and stuff like that, to just use some address-bar API and change the url that way. However, that's not something I have any plans for.
